# Generated by Django 4.2.3 on 2024-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedproject',
            name='app',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedproject',
            name='application',
            field=models.TextField(default='value'),
        ),
        migrations.AddField(
            model_name='generatedproject',
            name='type_bd',
            field=models.CharField(choices=[('postgres', 'Postgres'), ('mysql', 'Mysql')], db_index=True, default='postgres', max_length=10, verbose_name='Type de Base de Données'),
        ),
    ]
